const phraseTranslations: Array<[RegExp, string]> = [
  [/\b3\/4\b/g, 'سه چهارم'],
  [/\balternate\b/g, 'متناوب'],
  [/\balternating\b/g, 'متناوب'],
  [/\bassisted\b/g, 'کمکی'],
  [/\bback extension\b/g, 'اکستنشن کمر'],
  [/\bbench press\b/g, 'پرس سینه'],
  [/\bbent over\b/g, 'خم شده'],
  [/\bbody weight\b/g, 'وزن بدن'],
  [/\bcalf raise\b/g, 'ساق پا'],
  [/\bchest press\b/g, 'پرس سینه'],
  [/\bclose grip\b/g, 'دست جمع'],
  [/\bdead lift\b/g, 'ددلیفت'],
  [/\bdeadlift\b/g, 'ددلیفت'],
  [/\bdecline\b/g, 'زیر سینه'],
  [/\bfront raise\b/g, 'نشر جلو'],
  [/\bgood morning\b/g, 'گود مورنینگ'],
  [/\bhammer curl\b/g, 'جلو بازو چکشی'],
  [/\bhigh knee\b/g, 'زانوی بلند'],
  [/\bhip thrust\b/g, 'هیپ تراست'],
  [/\bincline\b/g, 'بالا سینه'],
  [/\bjumping jack\b/g, 'پروانه'],
  [/\blat pulldown\b/g, 'لت پول‌داون'],
  [/\blateral raise\b/g, 'نشر جانب'],
  [/\bleg curl\b/g, 'پشت پا'],
  [/\bleg extension\b/g, 'جلو پا دستگاه'],
  [/\bleg press\b/g, 'پرس پا'],
  [/\blying\b/g, 'خوابیده'],
  [/\bmountain climber\b/g, 'کوه‌نوردی'],
  [/\bpull up\b/g, 'بارفیکس'],
  [/\bpulldown\b/g, 'پول‌داون'],
  [/\bpush up\b/g, 'شنا'],
  [/\brear delt\b/g, 'دلتوئید خلفی'],
  [/\breverse grip\b/g, 'گرفتن معکوس'],
  [/\brussian twist\b/g, 'چرخش روسی'],
  [/\bshoulder press\b/g, 'پرس سرشانه'],
  [/\bside plank\b/g, 'پلانک پهلو'],
  [/\bsingle arm\b/g, 'تک دست'],
  [/\bsingle leg\b/g, 'تک پا'],
  [/\bsit up\b/g, 'دراز نشست'],
  [/\bsplit squat\b/g, 'اسکوات اسپلیت'],
  [/\bstiff leg\b/g, 'پا صاف'],
  [/\bstraight arm\b/g, 'دست صاف'],
  [/\btriceps extension\b/g, 'پشت بازو اکستنشن'],
  [/\bupright row\b/g, 'کول هالتر'],
  [/\bwide grip\b/g, 'دست باز'],
];

const wordTranslations = new Map<string, string>([
  ['ab', 'شکم'],
  ['abs', 'شکم'],
  ['adductor', 'داخل ران'],
  ['air', 'هوایی'],
  ['ankle', 'مچ پا'],
  ['arm', 'بازو'],
  ['arms', 'بازوها'],
  ['around', 'دورانی'],
  ['back', 'کمر'],
  ['ball', 'توپ'],
  ['band', 'کش'],
  ['bar', 'میله'],
  ['barbell', 'هالتر'],
  ['battle', 'بتل'],
  ['bench', 'نیمکت'],
  ['biceps', 'جلو بازو'],
  ['bike', 'دوچرخه'],
  ['bodyweight', 'وزن بدن'],
  ['bosu', 'بوسو'],
  ['box', 'جعبه'],
  ['bridge', 'پل'],
  ['burpee', 'برپی'],
  ['butterfly', 'فلای'],
  ['cable', 'کابل'],
  ['calf', 'ساق'],
  ['captains', 'کاپیتان'],
  ['cardio', 'هوازی'],
  ['chair', 'صندلی'],
  ['chest', 'سینه'],
  ['chin', 'چانه'],
  ['circle', 'دایره'],
  ['clean', 'کلین'],
  ['climber', 'کوه‌نورد'],
  ['close', 'جمع'],
  ['cobra', 'کبرا'],
  ['concentration', 'تمرکزی'],
  ['cross', 'ضربدری'],
  ['crunch', 'کرانچ'],
  ['curl', 'جلو بازو'],
  ['dead', 'مرده'],
  ['dip', 'دیپ'],
  ['donkey', 'دانکی'],
  ['down', 'پایین'],
  ['dragon', 'دراگون'],
  ['drop', 'دراپ'],
  ['dumbbell', 'دمبل'],
  ['elbow', 'آرنج'],
  ['elliptical', 'الپتیکال'],
  ['extension', 'اکستنشن'],
  ['face', 'صورت'],
  ['flat', 'صاف'],
  ['flexion', 'فلکشن'],
  ['floor', 'زمین'],
  ['fly', 'فلای'],
  ['forward', 'رو به جلو'],
  ['front', 'جلو'],
  ['glute', 'باسن'],
  ['glutes', 'باسن'],
  ['good', 'گود'],
  ['grip', 'گرفتن'],
  ['hack', 'هاک'],
  ['half', 'نیمه'],
  ['hammer', 'چکشی'],
  ['hand', 'دست'],
  ['head', 'سر'],
  ['high', 'بلند'],
  ['hip', 'لگن'],
  ['hyperextension', 'هایپراکستنشن'],
  ['jack', 'پروانه'],
  ['jump', 'پرش'],
  ['jumping', 'پرشی'],
  ['kettlebell', 'کتل‌بل'],
  ['kick', 'کیک'],
  ['kickback', 'کیک‌بک'],
  ['knee', 'زانو'],
  ['kneeling', 'زانو زده'],
  ['lat', 'لت'],
  ['lateral', 'جانبی'],
  ['leg', 'پا'],
  ['lever', 'اهرم'],
  ['leverage', 'دستگاه'],
  ['lift', 'لیفت'],
  ['low', 'پایین'],
  ['lower', 'پایینی'],
  ['lunge', 'لانج'],
  ['machine', 'دستگاه'],
  ['march', 'مارچ'],
  ['military', 'نظامی'],
  ['morning', 'مورنینگ'],
  ['neck', 'گردن'],
  ['neutral', 'خنثی'],
  ['one', 'تک'],
  ['over', 'خم'],
  ['pec', 'سینه'],
  ['plank', 'پلانک'],
  ['press', 'پرس'],
  ['pull', 'کشش'],
  ['pullover', 'پول‌اور'],
  ['push', 'فشار'],
  ['raise', 'بالا بردن'],
  ['rear', 'پشت'],
  ['reverse', 'معکوس'],
  ['roll', 'رول'],
  ['rope', 'طناب'],
  ['rotation', 'چرخش'],
  ['row', 'قایقی'],
  ['run', 'دویدن'],
  ['russian', 'روسی'],
  ['seated', 'نشسته'],
  ['shoulder', 'سرشانه'],
  ['shrug', 'شراگ'],
  ['side', 'پهلو'],
  ['single', 'تک'],
  ['sit', 'نشستن'],
  ['skullcrusher', 'اسکال‌کراشر'],
  ['sled', 'سورتمه'],
  ['smith', 'اسمیت'],
  ['snatch', 'اسنچ'],
  ['spin', 'چرخشی'],
  ['split', 'اسپلیت'],
  ['squat', 'اسکوات'],
  ['standing', 'ایستاده'],
  ['step', 'استپ'],
  ['stiff', 'صاف'],
  ['straight', 'صاف'],
  ['stretch', 'کشش'],
  ['sumo', 'سومو'],
  ['superman', 'سوپرمن'],
  ['support', 'حمایتی'],
  ['swing', 'تاب'],
  ['t', 'تی'],
  ['thigh', 'ران'],
  ['to', 'به'],
  ['toe', 'پنجه'],
  ['touch', 'لمس'],
  ['trap', 'کول'],
  ['triceps', 'پشت بازو'],
  ['twist', 'چرخش'],
  ['up', 'بالا'],
  ['upper', 'بالایی'],
  ['v', 'وی'],
  ['walk', 'راه رفتن'],
  ['walking', 'راه رفتنی'],
  ['wall', 'دیوار'],
  ['weighted', 'وزنه‌دار'],
  ['wheel', 'چرخ'],
  ['wide', 'باز'],
  ['wrist', 'مچ'],
]);

export function translateExerciseNameToPersian(name: string): string {
  let translatedName = name.toLowerCase().replace(/[()]/g, ' ');

  for (const [pattern, translation] of phraseTranslations) {
    translatedName = translatedName.replace(pattern, ` ${translation} `);
  }

  return translatedName
    .split(/([\s,/-]+)/)
    .map((token) => {
      const normalizedToken = token.trim();

      if (!normalizedToken || /[\s,/-]+/.test(token)) {
        return token;
      }

      return wordTranslations.get(normalizedToken) ?? token;
    })
    .join('')
    .replace(/\s+/g, ' ')
    .trim();
}

